server:
  port: 8101
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 251212
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: yewa
    password: 251212
    virtualHost: /
    publisherConfirms: true
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiagehao/SpringcloudConfig.git #配置git仓库地址
          searchPaths: respo #配置仓库路径
          #username: ****** #访问git仓库的用户名
          #password: ****** #访问git仓库的用户密码
      label: master #配置仓库的分支
    inetutils:
      preferred-networks: 127.0.0.1
    client:
      ip-address: 127.0.0.1
eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/