server:
  port: 8888
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 251212
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: yewa
    password: 251212
  application:
    name: register
  profiles:
    active: dev
eureka:
  server:
    #开启自我保护
    enable-self-preservation: true
  instance:
    #以IP地址注册
#    preferIpAddress: true
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/